In [1]:
from google.colab import files
uploaded = files.upload()

Saving SuperStoreOrders.csv to SuperStoreOrders.csv

In [39]:
print("24BAD058")
import pandas as pd
import numpy as np

24BAD058

In [3]:
df = pd.read_csv("SuperStoreOrders.csv")

In [4]:
df.head()
df.shape
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        51290 non-null  object
 1   order_date      51290 non-null  object
 2   ship_date       51290 non-null  object
 3   ship_mode       51290 non-null  object
 4   customer_name   51290 non-null  object
 5   segment         51290 non-null  object
 6   state           51290 non-null  object
 7   country         51290 non-null  object
 8   market          51290 non-null  object
 9   region          51290 non-null  object
 10  product_id      51290 non-null  object
 11  category        51290 non-null  object
 12  sub_category    51290 non-null  object
 13  product_name    51290 non-null  object
 14  sales           51290 non-null  object
 15  quantity        51290 non-null  int64
 16  discount        51290 non-null  float64
 17  profit          51290 non-null  float64
 18  shipping_cost   51290 non-null  float64
 19  order_priority  51290 non-null  object
 20  year            51290 non-null  int64
dtypes: float64(3), int64(2), object(16)
memory usage: 8.2+ MB

In [5]:
print("Shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nMissing values:")
print(df.isnull().sum())

Shape: (51290, 21)

Columns:
['order_id', 'order_date', 'ship_date', 'ship_mode', 'customer_name', 'segment', 'state', 'country', 'market', 'region', 'product_id', 'category', 'sub_category', 'product_name', 'sales', 'quantity', 'discount', 'profit', 'shipping_cost', 'order_priority', 'year']

Missing values:
order_id          0
order_date        0
ship_date         0
ship_mode         0
customer_name     0
segment           0
state             0
country           0
market            0
region            0
product_id        0
category          0
sub_category      0
product_name      0
sales             0
quantity          0
discount          0
profit            0
shipping_cost     0
order_priority    0
year              0
dtype: int64

In [6]:
messy_df = df.copy()

In [7]:
messy_df.loc[5, "sales"] = np.nan
messy_df.loc[20, "region"] = np.nan
messy_df.loc[50, "quantity"] = np.nan

In [8]:
messy_df.isnull().sum()

order_id          0
order_date        0
ship_date         0
ship_mode         0
customer_name     0
segment           0
state             0
country           0
market            0
region            1
product_id        0
category          0
sub_category      0
product_name      0
sales             1
quantity          1
discount          0
profit            0
shipping_cost     0
order_priority    0
year              0
dtype: int64

In [9]:
messy_df.loc[100, "sales"] = 10000000
messy_df.loc[100, ["order_id", "product_name", "sales"]]

order_id                            IN-2011-61302
product_name    Nokia Smart Phone, with Caller ID
sales                                    10000000
Name: 100, dtype: object

In [10]:
messy_df.loc[10, "order_date"] = "15/01/2012"
messy_df.loc[11, "order_date"] = "2012-02-20"
messy_df.loc[12, "order_date"] = "March 25, 2012"
messy_df.loc[10:12, "order_date"]

10        15/01/2012
11        2012-02-20
12    March 25, 2012
Name: order_date, dtype: object

In [14]:
# --- Handling Missing Values in messy_df ---

print("Original missing values:")
print(messy_df.isnull().sum())
print("\n" + "="*50 + "\n")

# Data Cleaning: Convert 'sales' and 'quantity' to numeric, handling potential non-numeric entries
# 'sales' often comes with commas as thousand separators in raw data
# 'quantity' could also be an object type if there were any non-numeric entries

messy_df['sales'] = messy_df['sales'].astype(str).str.replace(',', '', regex=False)
messy_df['sales'] = pd.to_numeric(messy_df['sales'], errors='coerce')

# Ensure 'quantity' is numeric as well, handling potential non-numeric entries
messy_df['quantity'] = pd.to_numeric(messy_df['quantity'], errors='coerce')

# 1. Handling 'sales' column (Numerical)
# Method: Impute with the median
# Reason: Sales is a numerical column, and using the median is a robust strategy
#         against potential outliers, which could skew the mean. It preserves
#         more of the original data distribution compared to dropping rows.
median_sales = messy_df['sales'].median()
messy_df['sales'] = messy_df['sales'].fillna(median_sales)
print(f"Filled missing 'sales' values with median: {median_sales:.2f}")

# 2. Handling 'quantity' column (Numerical)
# Method: Impute with the median
# Reason: Quantity is also numerical. Similar to sales, median imputation
#         is robust to outliers. Since quantity represents counts, median is
#         often a good central tendency measure. One could also consider
#         the mode, but median is a general robust choice for numerical data.
median_quantity = messy_df['quantity'].median()
messy_df['quantity'] = messy_df['quantity'].fillna(median_quantity)
print(f"Filled missing 'quantity' values with median: {median_quantity:.0f}")

# 3. Handling 'region' column (Categorical)
# Method: Impute with the mode
# Reason: Region is a categorical column. Replacing missing values with the
#         most frequent category (mode) is a common and suitable approach
#         as it maintains the distribution of the existing categories and
#         introduces the most representative value for the missing entries.
#         We use `.mode()[0]` because `.mode()` can return multiple values if there's a tie.
mode_region = messy_df['region'].mode()[0]
messy_df['region'] = messy_df['region'].fillna(mode_region)
print(f"Filled missing 'region' values with mode: {mode_region}")

print("\n" + "="*50 + "\n")
print("Missing values after imputation:")
print(messy_df.isnull().sum())

Original missing values:
order_id          0
order_date        0
ship_date         0
ship_mode         0
customer_name     0
segment           0
state             0
country           0
market            0
region            0
product_id        0
category          0
sub_category      0
product_name      0
sales             0
quantity          0
discount          0
profit            0
shipping_cost     0
order_priority    0
year              0
dtype: int64

==================================================

Filled missing 'sales' values with median: 85.00
Filled missing 'quantity' values with median: 3
Filled missing 'region' values with mode: Central

==================================================

Missing values after imputation:
order_id          0
order_date        0
ship_date         0
ship_mode         0
customer_name     0
segment           0
state             0
country           0
market            0
region            0
product_id        0
category          0
sub_category      0
product_name      0
sales             0
quantity          0
discount          0
profit            0
shipping_cost     0
order_priority    0
year              0
dtype: int64

In [15]:
Q1 = messy_df["sales"].quantile(0.25)
Q3 = messy_df["sales"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = messy_df[
    (messy_df["sales"] < lower_bound) |
    (messy_df["sales"] > upper_bound)
]

print(outliers[["order_id", "sales"]])

              order_id   sales
8        ID-2011-80230   912.0
9         IZ-2011-4680   667.0
12     ES-2011-4869686   854.0
27      MX-2011-111255  1648.0
43      MX-2011-109267  3029.0
...                ...     ...
51229    IN-2014-43550  1091.0
51230     RS-2014-1460   866.0
51231    IN-2014-30390  1049.0
51232  ES-2014-3458802   867.0
51239    ID-2014-54442   685.0

[5655 rows x 2 columns]

In [16]:
print(messy_df.isnull().sum())

order_id          0
order_date        0
ship_date         0
ship_mode         0
customer_name     0
segment           0
state             0
country           0
market            0
region            0
product_id        0
category          0
sub_category      0
product_name      0
sales             0
quantity          0
discount          0
profit            0
shipping_cost     0
order_priority    0
year              0
dtype: int64

In [17]:
messy_df["sales"] = messy_df["sales"].clip(
    lower=lower_bound,
    upper=upper_bound
)
print(messy_df["sales"].max())

581.0

In [18]:
messy_df["order_date"] = pd.to_datetime(
    messy_df["order_date"],
    errors="coerce"
)
print(messy_df["order_date"].head())

0   2011-01-01
1   2011-01-01
2   2011-01-01
3   2011-01-01
4   2011-01-01
Name: order_date, dtype: datetime64[ns]

In [19]:
print(
    "Invalid dates:",
    messy_df["order_date"].isnull().sum()
)

Invalid dates: 31226

In [20]:
messy_df["year"] = messy_df["order_date"].dt.year

messy_df["quarter"] = (
    "Q" + messy_df["order_date"].dt.quarter.astype(str)
)

messy_df["month"] = messy_df["order_date"].dt.month

messy_df["month_name"] = messy_df["order_date"].dt.month_name()

In [21]:
messy_df[
    ["order_date", "year", "quarter", "month", "month_name"]
].head()

  order_date    year quarter  month month_name
0 2011-01-01  2011.0    Q1.0    1.0    January
1 2011-01-01  2011.0    Q1.0    1.0    January
2 2011-01-01  2011.0    Q1.0    1.0    January
3 2011-01-01  2011.0    Q1.0    1.0    January
4 2011-01-01  2011.0    Q1.0    1.0    January

In [22]:
bi_data = (
    messy_df
    .groupby(
        ["region", "year", "quarter", "month"],
        as_index=False
    )["sales"]
    .sum()
)

In [23]:
bi_data.head(20)

    region    year quarter  month   sales
0   Africa  2011.0    Q1.0    1.0  2784.0
1   Africa  2011.0    Q1.0    2.0  3407.0
2   Africa  2011.0    Q1.0    3.0  4094.0
3   Africa  2011.0    Q2.0    4.0  3161.0
4   Africa  2011.0    Q2.0    5.0  1909.0
5   Africa  2011.0    Q2.0    6.0  1002.0
6   Africa  2011.0    Q3.0    7.0  3354.0
7   Africa  2011.0    Q3.0    8.0  4300.0
8   Africa  2011.0    Q3.0    9.0   855.0
9   Africa  2011.0    Q4.0   10.0  4351.0
10  Africa  2011.0    Q4.0   11.0  2262.0
11  Africa  2011.0    Q4.0   12.0  4925.0
12  Africa  2012.0    Q1.0    1.0  1347.0
13  Africa  2012.0    Q1.0    2.0  5515.0
14  Africa  2012.0    Q1.0    3.0  2853.0
15  Africa  2012.0    Q2.0    4.0  2604.0
16  Africa  2012.0    Q2.0    5.0  2225.0
17  Africa  2012.0    Q2.0    6.0  3902.0
18  Africa  2012.0    Q3.0    7.0  6255.0
19  Africa  2012.0    Q3.0    8.0   960.0

In [24]:
bi_data.to_csv(
    "BI_Ready_Sales.csv",
    index=False
)

In [25]:
region_sales = (
    messy_df
    .groupby("region")["sales"]
    .sum()
    .reset_index()
)

In [26]:
region_sales["sales_rank"] = (
    region_sales["sales"]
    .rank(
        ascending=False,
        method="dense"
    )
)

In [27]:
region_sales.sort_values("sales_rank")
monthly_sales = (
    messy_df
    .groupby(
        ["year", "month"],
        as_index=False
    )["sales"]
    .sum()
)

In [28]:
monthly_sales = monthly_sales.sort_values(
    ["year", "month"]
)
monthly_sales["previous_month_sales"] = (
    monthly_sales["sales"].shift(1)
)
monthly_sales.head(15)

      year  month    sales  previous_month_sales
0   2011.0    1.0  59669.0                   NaN
1   2011.0    2.0  60148.0               59669.0
2   2011.0    3.0  55207.0               60148.0
3   2011.0    4.0  46561.0               55207.0
4   2011.0    5.0  38207.0               46561.0
5   2011.0    6.0  47008.0               38207.0
6   2011.0    7.0  58764.0               47008.0
7   2011.0    8.0  60339.0               58764.0
8   2011.0    9.0  53053.0               60339.0
9   2011.0   10.0  47080.0               53053.0
10  2011.0   11.0  45039.0               47080.0
11  2011.0   12.0  48699.0               45039.0
12  2012.0    1.0  53463.0               48699.0
13  2012.0    2.0  65174.0               53463.0
14  2012.0    3.0  63673.0               65174.0

In [29]:
monthly_sales["cumulative_sales"] = (
    monthly_sales["sales"].cumsum()
)
monthly_sales.head(15)

      year  month    sales  previous_month_sales  cumulative_sales
0   2011.0    1.0  59669.0                   NaN           59669.0
1   2011.0    2.0  60148.0               59669.0          119817.0
2   2011.0    3.0  55207.0               60148.0          175024.0
3   2011.0    4.0  46561.0               55207.0          221585.0
4   2011.0    5.0  38207.0               46561.0          259792.0
5   2011.0    6.0  47008.0               38207.0          306800.0
6   2011.0    7.0  58764.0               47008.0          365564.0
7   2011.0    8.0  60339.0               58764.0          425903.0
8   2011.0    9.0  53053.0               60339.0          478956.0
9   2011.0   10.0  47080.0               53053.0          526036.0
10  2011.0   11.0  45039.0               47080.0          571075.0
11  2011.0   12.0  48699.0               45039.0          619774.0
12  2012.0    1.0  53463.0               48699.0          673237.0
13  2012.0    2.0  65174.0               53463.0          738411.0
14  2012.0    3.0  63673.0               65174.0          802084.0

In [30]:
region_month = (
    messy_df
    .groupby(
        ["region", "year", "month"],
        as_index=False
    )["sales"]
    .sum()
)

region_month = region_month.sort_values(
    ["region", "year", "month"]
)

In [31]:
region_month["cumulative_sales"] = (
    region_month
    .groupby("region")["sales"]
    .cumsum()
)

In [32]:
region_month["monthly_rank"] = (
    region_month
    .groupby("region")["sales"]
    .rank(
        ascending=False,
        method="dense"
    )
)

In [33]:
analysis = region_month.copy()

analysis.head(20)

    region    year  month   sales  cumulative_sales  monthly_rank
0   Africa  2011.0    1.0  2784.0            2784.0          38.0
1   Africa  2011.0    2.0  3407.0            6191.0          32.0
2   Africa  2011.0    3.0  4094.0           10285.0          27.0
3   Africa  2011.0    4.0  3161.0           13446.0          36.0
4   Africa  2011.0    5.0  1909.0           15355.0          43.0
5   Africa  2011.0    6.0  1002.0           16357.0          46.0
6   Africa  2011.0    7.0  3354.0           19711.0          34.0
7   Africa  2011.0    8.0  4300.0           24011.0          26.0
8   Africa  2011.0    9.0   855.0           24866.0          48.0
9   Africa  2011.0   10.0  4351.0           29217.0          25.0
10  Africa  2011.0   11.0  2262.0           31479.0          41.0
11  Africa  2011.0   12.0  4925.0           36404.0          23.0
12  Africa  2012.0    1.0  1347.0           37751.0          44.0
13  Africa  2012.0    2.0  5515.0           43266.0          21.0
14  Africa  2012.0    3.0  2853.0           46119.0          37.0
15  Africa  2012.0    4.0  2604.0           48723.0          39.0
16  Africa  2012.0    5.0  2225.0           50948.0          42.0
17  Africa  2012.0    6.0  3902.0           54850.0          29.0
18  Africa  2012.0    7.0  6255.0           61105.0          16.0
19  Africa  2012.0    8.0   960.0           62065.0          47.0

In [34]:
analysis = analysis[
    [
        "region",
        "year",
        "month",
        "sales",
        "monthly_rank",
        "cumulative_sales"
    ]
]

In [35]:
analysis.head(20)

    region    year  month   sales  monthly_rank  cumulative_sales
0   Africa  2011.0    1.0  2784.0          38.0            2784.0
1   Africa  2011.0    2.0  3407.0          32.0            6191.0
2   Africa  2011.0    3.0  4094.0          27.0           10285.0
3   Africa  2011.0    4.0  3161.0          36.0           13446.0
4   Africa  2011.0    5.0  1909.0          43.0           15355.0
5   Africa  2011.0    6.0  1002.0          46.0           16357.0
6   Africa  2011.0    7.0  3354.0          34.0           19711.0
7   Africa  2011.0    8.0  4300.0          26.0           24011.0
8   Africa  2011.0    9.0   855.0          48.0           24866.0
9   Africa  2011.0   10.0  4351.0          25.0           29217.0
10  Africa  2011.0   11.0  2262.0          41.0           31479.0
11  Africa  2011.0   12.0  4925.0          23.0           36404.0
12  Africa  2012.0    1.0  1347.0          44.0           37751.0
13  Africa  2012.0    2.0  5515.0          21.0           43266.0
14  Africa  2012.0    3.0  2853.0          37.0           46119.0
15  Africa  2012.0    4.0  2604.0          39.0           48723.0
16  Africa  2012.0    5.0  2225.0          42.0           50948.0
17  Africa  2012.0    6.0  3902.0          29.0           54850.0
18  Africa  2012.0    7.0  6255.0          16.0           61105.0
19  Africa  2012.0    8.0   960.0          47.0           62065.0

In [36]:
region_month["monthly_rank"] = (
    region_month
    .groupby("region")["sales"]
    .rank(
        ascending=False,
        method="dense"
    )
)

monthly_sales["previous_month_sales"] = (
    monthly_sales["sales"].shift(1)
)

region_month["cumulative_sales"] = (
    region_month
    .groupby("region")["sales"]
    .cumsum()
)

In [37]:
print("Missing values:")
print(messy_df.isnull().sum())

print("\nFinal shape:")
print(messy_df.shape)

print("\nBI data:")
display(bi_data.head())

print("\nRegion ranking:")
display(region_sales.sort_values("sales_rank"))

print("\nMonthly analysis:")
display(monthly_sales.head())

print("\nRegion analytical table:")
display(analysis.head(20))

Missing values:
order_id              0
order_date        31226
ship_date             0
ship_mode             0
customer_name         0
segment               0
state                 0
country               0
market                0
region                0
product_id            0
category              0
sub_category          0
product_name          0
sales                 0
quantity              0
discount              0
profit                0
shipping_cost         0
order_priority        0
year              31226
quarter               0
month             31226
month_name        31226
dtype: int64

Final shape:
(51290, 24)

BI data:

   region    year quarter  month   sales
0  Africa  2011.0    Q1.0    1.0  2784.0
1  Africa  2011.0    Q1.0    2.0  3407.0
2  Africa  2011.0    Q1.0    3.0  4094.0
3  Africa  2011.0    Q2.0    4.0  3161.0
4  Africa  2011.0    Q2.0    5.0  1909.0

Region ranking:

            region      sales  sales_rank
3          Central  2015500.0         1.0
10           South  1142356.0         2.0
7            North   888253.0         3.0
9          Oceania   721453.0         4.0
5             EMEA   628903.0         5.0
11  Southeast Asia   615365.0         6.0
0           Africa   591775.0         7.0
8       North Asia   539867.0         8.0
12            West   491019.0         9.0
4     Central Asia   459888.0        10.0
6             East   425083.0        11.0
2        Caribbean   264781.0        12.0
1           Canada    53642.0        13.0

Monthly analysis:

     year  month    sales  previous_month_sales  cumulative_sales
0  2011.0    1.0  59669.0                   NaN           59669.0
1  2011.0    2.0  60148.0               59669.0          119817.0
2  2011.0    3.0  55207.0               60148.0          175024.0
3  2011.0    4.0  46561.0               55207.0          221585.0
4  2011.0    5.0  38207.0               46561.0          259792.0

Region analytical table:

    region    year  month   sales  monthly_rank  cumulative_sales
0   Africa  2011.0    1.0  2784.0          38.0            2784.0
1   Africa  2011.0    2.0  3407.0          32.0            6191.0
2   Africa  2011.0    3.0  4094.0          27.0           10285.0
3   Africa  2011.0    4.0  3161.0          36.0           13446.0
4   Africa  2011.0    5.0  1909.0          43.0           15355.0
5   Africa  2011.0    6.0  1002.0          46.0           16357.0
6   Africa  2011.0    7.0  3354.0          34.0           19711.0
7   Africa  2011.0    8.0  4300.0          26.0           24011.0
8   Africa  2011.0    9.0   855.0          48.0           24866.0
9   Africa  2011.0   10.0  4351.0          25.0           29217.0
10  Africa  2011.0   11.0  2262.0          41.0           31479.0
11  Africa  2011.0   12.0  4925.0          23.0           36404.0
12  Africa  2012.0    1.0  1347.0          44.0           37751.0
13  Africa  2012.0    2.0  5515.0          21.0           43266.0
14  Africa  2012.0    3.0  2853.0          37.0           46119.0
15  Africa  2012.0    4.0  2604.0          39.0           48723.0
16  Africa  2012.0    5.0  2225.0          42.0           50948.0
17  Africa  2012.0    6.0  3902.0          29.0           54850.0
18  Africa  2012.0    7.0  6255.0          16.0           61105.0
19  Africa  2012.0    8.0   960.0          47.0           62065.0